# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: #1C2F2F;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: #304343;\n"
"    border: 0px;\n"
"    height: 20 px;\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #345656;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #2F4141;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background: #304343;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    border: 0px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    background: #405959;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"     border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgba(255, 255, 255, 0);\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    selection-background-color: #405959;\n"
"    color: white;\n"
"}\n"
"\n"
"QFrame {\n"
"    background: #253636;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background: #304343;\n"
"    color: white;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    background: #7976B8;\n"
"    color: white;\n"
"    border: 0px;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background: #A65353;\n"
"    color: white;\n"
"    border: 0px;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: #253636;\n"
"    color: white;\n"
"    padding-left: 6px;\n"
"    border-radius: 4px;\n"
"    border: 0px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_cursor = QtWidgets.QPushButton(self.frame_3)
        self.btn_cursor.setObjectName("btn_cursor")
        self.horizontalLayout_2.addWidget(self.btn_cursor)
        self.btn_brush = QtWidgets.QPushButton(self.frame_3)
        self.btn_brush.setObjectName("btn_brush")
        self.horizontalLayout_2.addWidget(self.btn_brush)
        self.btn_text = QtWidgets.QPushButton(self.frame_3)
        self.btn_text.setObjectName("btn_text")
        self.horizontalLayout_2.addWidget(self.btn_text)
        self.horizontalLayout_3.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_tool = QtWidgets.QLabel(self.frame_4)
        self.label_tool.setObjectName("label_tool")
        self.horizontalLayout_3.addWidget(self.label_tool)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.brush_size = QtWidgets.QSpinBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.brush_size.setFont(font)
        self.brush_size.setMinimum(1)
        self.brush_size.setMaximum(100)
        self.brush_size.setProperty("value", 3)
        self.brush_size.setObjectName("brush_size")
        self.horizontalLayout_3.addWidget(self.brush_size)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.text_size = QtWidgets.QSpinBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_size.setFont(font)
        self.text_size.setMinimum(8)
        self.text_size.setMaximum(80)
        self.text_size.setProperty("value", 17)
        self.text_size.setObjectName("text_size")
        self.horizontalLayout_3.addWidget(self.text_size)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.brush_color = QtWidgets.QPushButton(self.frame_4)
        self.brush_color.setObjectName("brush_color")
        self.horizontalLayout_3.addWidget(self.brush_color)
        self.text_color = QtWidgets.QPushButton(self.frame_4)
        self.text_color.setObjectName("text_color")
        self.horizontalLayout_3.addWidget(self.text_color)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lang_from = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang_from.setFont(font)
        self.lang_from.setCurrentText("")
        self.lang_from.setObjectName("lang_from")
        self.horizontalLayout.addWidget(self.lang_from)
        self.btn_reverse = QtWidgets.QPushButton(self.frame_2)
        self.btn_reverse.setObjectName("btn_reverse")
        self.horizontalLayout.addWidget(self.btn_reverse)
        self.lang_to = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang_to.setFont(font)
        self.lang_to.setObjectName("lang_to")
        self.horizontalLayout.addWidget(self.lang_to)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit.sizePolicy().hasHeightForWidth())
        self.line_edit.setSizePolicy(sizePolicy)
        self.line_edit.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit.setFont(font)
        self.line_edit.setObjectName("line_edit")
        self.verticalLayout.addWidget(self.line_edit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FIT - Fast Image Translate"))
        self.btn_cursor.setText(_translate("MainWindow", "Cursor"))
        self.btn_brush.setText(_translate("MainWindow", "Brush"))
        self.btn_text.setText(_translate("MainWindow", "Add Text"))
        self.label_tool.setText(_translate("MainWindow", "Selected: Cursor"))
        self.label_2.setText(_translate("MainWindow", "Brush size:"))
        self.label_3.setText(_translate("MainWindow", "Text size:"))
        self.brush_color.setText(_translate("MainWindow", "Brush Color"))
        self.text_color.setText(_translate("MainWindow", "Text Color"))
        self.btn_reverse.setText(_translate("MainWindow", "<->"))
        self.label.setText(_translate("MainWindow", "Paste your image with Ctrl + V"))
        self.line_edit.setPlaceholderText(_translate("MainWindow", "Your text here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
