# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: #1C2F2F;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: #304343;\n"
"    border: 0px;\n"
"    height: 20 px;\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #345656;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #2F4141;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background: #304343;\n"
"    border-radius: 4px;\n"
"    padding: 8px;\n"
"    color: white;\n"
"    border: 0px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    background: #405959;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"     border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: rgba(255, 255, 255, 0);\n"
"    padding: 10px;\n"
"    border: 0px;\n"
"    selection-background-color: #405959;\n"
"    color: white;\n"
"}\n"
"\n"
"QFrame {\n"
"    background: #253636;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_cursor = QtWidgets.QPushButton(self.frame_3)
        self.btn_cursor.setObjectName("btn_cursor")
        self.horizontalLayout_2.addWidget(self.btn_cursor)
        self.btn_brush = QtWidgets.QPushButton(self.frame_3)
        self.btn_brush.setObjectName("btn_brush")
        self.horizontalLayout_2.addWidget(self.btn_brush)
        self.btn_text = QtWidgets.QPushButton(self.frame_3)
        self.btn_text.setObjectName("btn_text")
        self.horizontalLayout_2.addWidget(self.btn_text)
        self.horizontalLayout.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lang_from = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang_from.setFont(font)
        self.lang_from.setCurrentText("")
        self.lang_from.setObjectName("lang_from")
        self.horizontalLayout.addWidget(self.lang_from)
        self.btn_reverse = QtWidgets.QPushButton(self.frame_2)
        self.btn_reverse.setObjectName("btn_reverse")
        self.horizontalLayout.addWidget(self.btn_reverse)
        self.lang_to = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lang_to.setFont(font)
        self.lang_to.setObjectName("lang_to")
        self.horizontalLayout.addWidget(self.lang_to)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FIT - Fast Image Translate"))
        self.btn_cursor.setText(_translate("MainWindow", "Cursor"))
        self.btn_brush.setText(_translate("MainWindow", "Brush"))
        self.btn_text.setText(_translate("MainWindow", "Text"))
        self.btn_reverse.setText(_translate("MainWindow", "<->"))
        self.label.setText(_translate("MainWindow", "Paste your image with Ctrl + V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
